
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev
    username: root
    password: root
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  secret: secretkey123